# Generated by Django 2.1.5 on 2021-05-09 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registercall', '0001_initial'),
        ('surveys', '0001_initial'),
        ('register_helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='notes')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
                ('helper_name', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_helper.Helper')),
                ('survey_task', models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.SurveyTask')),
                ('task', models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to='registercall.Task')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Note'),
        ),
    ]
