# Generated by Django 2.1.5 on 2021-11-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='image',
            field=models.FileField(blank=True, upload_to='notes'),
        ),
    ]
