# Generated by Django 2.1.5 on 2021-05-09 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registercall', '0001_initial'),
        ('surveys', '0001_initial'),
        ('management', '0001_initial'),
        ('ivr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='misc_audio',
            name='helpline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.HelpLine'),
        ),
        migrations.AddField(
            model_name='misc_audio',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivr.Language'),
        ),
        migrations.AddField(
            model_name='language',
            name='helpline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.HelpLine'),
        ),
        migrations.AddField(
            model_name='ivr_audio',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.HelperCategory'),
        ),
        migrations.AddField(
            model_name='ivr_audio',
            name='helpline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.HelpLine'),
        ),
        migrations.AddField(
            model_name='ivr_audio',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivr.Language'),
        ),
        migrations.AddField(
            model_name='feedbacktype',
            name='helpline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.HelpLine'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='feedbackType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivr.FeedbackType'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedbackresponses',
            field=models.ManyToManyField(blank=True, null=True, to='ivr.FeedbackResponse'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registercall.Task'),
        ),
        migrations.AddField(
            model_name='call_forward_details',
            name='survey_task',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.SurveyTask'),
        ),
        migrations.AddField(
            model_name='call_forward_details',
            name='task',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to='registercall.Task'),
        ),
        migrations.AddField(
            model_name='call_forward',
            name='survey_task',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.SurveyTask'),
        ),
        migrations.AddField(
            model_name='call_forward',
            name='task',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to='registercall.Task'),
        ),
    ]
