# Generated by Django 2.1.5 on 2021-05-09 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registercall', '0001_initial'),
        ('register_helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp')),
                ('action_type', models.IntegerField(choices=[(1, 'Primary'), (2, 'Specialist'), (3, 'Specialist Confirm'), (4, 'Feedback')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'Assign Pending'), (2, 'Assigned'), (3, 'Assigned Timeout'), (4, 'Rejected'), (5, 'Complete Timeout'), (6, 'Completed')], default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='registercall.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('accepted', models.DateTimeField(null=True, verbose_name='Accepted Timestamp')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Timeout'), (5, 'Closed'), (6, 'Completed'), (7, 'Reallocated'), (8, 'FAccepted'), (9, 'FCompleted')], default=1)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='task_manager.Action')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='register_helper.Helper')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=13)),
                ('comment', models.CharField(default=None, max_length=512, null=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helper', to='register_helper.Helper')),
            ],
        ),
        migrations.CreateModel(
            name='QandA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('question', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('answer', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('message', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_and_a', to='registercall.Task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default=None, max_length=512, null=True)),
                ('reallocateDate', models.DateTimeField(auto_now_add=True, verbose_name='Reallocated Timestamp')),
                ('fromHelper', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromhelper', to='register_helper.Helper')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskhist', to='registercall.Task')),
                ('toHelper', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tohelper', to='register_helper.Helper')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='q_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_and_a', to='task_manager.QandA'),
        ),
    ]
