# Generated by Django 2.1.5 on 2021-05-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('client_number', models.CharField(max_length=16, unique=True)),
                ('lastSMSSent', models.DateTimeField(auto_now=True, null=True, verbose_name='Last SMS Timestamp')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Blocked')], default=1)),
            ],
        ),
    ]
