# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_assign_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='helper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='register_helper.Helper'),
        ),
    ]
