# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registercall', '0014_auto_20160812_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='register_client.Client'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
