# Generated by Django 2.1.5 on 2021-05-09 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registercall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
                ('sent', models.BooleanField(blank=True, default=False)),
                ('language', models.TextField(blank=True, null=True)),
                ('from_doctor', models.BooleanField(default=False)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='attachments/')),
                ('is_synced', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_seen', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppUser',
            fields=[
                ('name', models.TextField(null=True)),
                ('contact', models.IntegerField(primary_key=True, serialize=False)),
                ('otp', models.TextField()),
                ('location', models.TextField(null=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('base32', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wwh_form_delivery.WhatsAppUser'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='wwh_task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registercall.Task'),
        ),
    ]
