# Generated by Django 2.1.5 on 2021-05-09 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register_client', '0001_initial'),
        ('register_helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpSurveyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_date', models.DateTimeField(auto_now_add=True, verbose_name='Marked Timestamp')),
                ('created_date', models.DateField(verbose_name='Created Timestamp')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('completed', 'completed')], default='pending', max_length=13)),
                ('create_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=13)),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_to_helper', to='register_helper.Helper')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('google_form_url', models.URLField(default=None, max_length=800, unique=True)),
                ('response_csv_url', models.URLField(default=None, max_length=800, unique=True)),
                ('number_of_people', models.IntegerField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
            ],
            options={
                'verbose_name_plural': '  Surveys',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_data', models.CharField(blank=True, max_length=10000)),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey')),
            ],
            options={
                'verbose_name_plural': 'Survey responses',
            },
        ),
        migrations.CreateModel(
            name='SurveyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_form_url', models.URLField(default=None, max_length=800, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('completed', 'completed'), ('followup_assigned', 'followup_assigned'), ('followup_completed', 'followup_completed')], default='pending', max_length=13)),
                ('tag_string', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('assignedDateTime', models.DateTimeField(blank=True, null=True, verbose_name='Assigned on')),
                ('completedDateTime', models.DateTimeField(blank=True, null=True, verbose_name='Completed on')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_client.Client')),
                ('helper', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='register_helper.Helper')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey')),
            ],
            options={
                'verbose_name_plural': ' Survey tasks',
            },
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.SurveyTask'),
        ),
        migrations.AddField(
            model_name='followupsurveytask',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_task', to='surveys.SurveyTask'),
        ),
        migrations.AddField(
            model_name='followupsurveytask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='f_task', to='surveys.SurveyTask'),
        ),
    ]
