# Generated by Django 2.1.5 on 2021-05-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveytask',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('completed', 'completed'), ('fo_assigned', 'fo_assigned'), ('fo_completed', 'fo_completed')], default='pending', max_length=13),
        ),
    ]
