# Generated by Django 2.1.5 on 2021-05-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20210510_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveytask',
            name='edit_form_url',
            field=models.URLField(default=None, max_length=800, null=True),
        ),
    ]
