# Generated by Django 2.1.5 on 2021-05-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20210510_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupsurveytask',
            name='marked_date',
            field=models.DateTimeField(verbose_name='Marked Timestamp'),
        ),
    ]
