# Generated by Django 2.1.5 on 2021-05-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20210510_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='google_form_url',
            field=models.URLField(default=None, max_length=800),
        ),
        migrations.AlterField(
            model_name='survey',
            name='response_csv_url',
            field=models.URLField(default=None, max_length=800),
        ),
    ]
