# Generated by Django 2.1.5 on 2021-06-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20210514_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='google_response_csv',
            field=models.FileField(blank=True, default=None, null=True, upload_to='survey'),
        ),
        migrations.AddField(
            model_name='survey',
            name='initial_csv',
            field=models.FileField(blank=True, default=None, null=True, upload_to='survey'),
        ),
    ]
