# Generated by Django 2.1.5 on 2021-05-09 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=None)),
                ('start_time', models.TimeField(verbose_name='StartTimeStamp')),
                ('end_time', models.TimeField(verbose_name='EndTimeStamp')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategorySubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=512)),
                ('subcategory', models.CharField(max_length=512)),
                ('language', models.CharField(choices=[('english', 'en'), ('hindi', 'hi'), ('gujarati', 'gj'), ('marathi', 'mr')], default='english', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='HelperCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='HelpLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General', max_length=64)),
                ('helpline_number', models.CharField(max_length=16, unique=True)),
                ('helpline_tollfree_number', models.CharField(default=None, max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelplineSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.IntegerField(default=1)),
                ('reassignment_time', models.IntegerField(default=3)),
                ('helpline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.HelpLine')),
            ],
        ),
        migrations.CreateModel(
            name='Tag_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=90)),
            ],
        ),
        migrations.AddField(
            model_name='helpercategory',
            name='helpline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.HelpLine'),
        ),
        migrations.AddField(
            model_name='categorysubcategory',
            name='helpline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.HelpLine'),
        ),
    ]
