# Generated by Django 2.1.5 on 2021-05-09 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('register_helper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableslot',
            name='helper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_helper.Helper'),
        ),
    ]
