# Generated by Django 2.1.5 on 2022-02-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_helper', '0001_initial'),
        ('management', '0002_availableslot_helper'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailableSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=None)),
                ('start_time', models.TimeField(verbose_name='StartTimeStamp')),
                ('end_time', models.TimeField(verbose_name='EndTimeStamp')),
                ('is_available', models.BooleanField(default=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_helper.Helper')),
            ],
        ),
    ]
