# Generated by Django 2.1.5 on 2022-02-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_doctoravailableslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailableslot',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='doctoravailableslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctoravailableslot',
            name='helper',
        ),
        migrations.RemoveField(
            model_name='doctoravailableslot',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='doctoravailableslot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='doctoravailableslot',
            name='doctor_id',
            field=models.IntegerField(default=0, verbose_name='DoctorID'),
        ),
        migrations.AddField(
            model_name='doctoravailableslot',
            name='doctor_name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='doctoravailableslot',
            name='slot_date',
            field=models.DateField(default='2022-02-12', verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='doctoravailableslot',
            name='slot_start_times',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
