# Generated by Django 2.1.5 on 2022-02-17 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_helper', '0001_initial'),
        ('registercall', '0002_auto_20210510_1706'),
        ('management', '0004_auto_20220213_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorBookedSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=512)),
                ('slot_date', models.DateField(verbose_name='Date')),
                ('slot_start_times', models.CharField(max_length=1024)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_helper.Helper')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registercall.Task')),
            ],
        ),
    ]
