# Generated by Django 2.1.5 on 2022-02-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_doctorbookedslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorbookedslot',
            old_name='slot_start_times',
            new_name='slot_time',
        ),
    ]
