# Generated by Django 2.1.5 on 2021-05-09 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register_client', '0001_initial'),
        ('ivr', '0001_initial'),
        ('management', '0001_initial'),
        ('register_helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Blocked'), (3, 'Merged')], default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='register_client.Client')),
                ('helpline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='management.HelpLine')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_date', models.DateTimeField(auto_now_add=True, verbose_name='Marked Timestamp')),
                ('created_date', models.DateField(verbose_name='Created Timestamp')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Rejected')], default=1)),
                ('create_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=13)),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_to', to='register_helper.Helper')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp')),
                ('tag_string', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('task_type', models.IntegerField(choices=[(1, 'DIRECT'), (2, 'INDIRECT')], default=2)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Rejected')], default=1)),
                ('call_attempt', models.IntegerField(default=0)),
                ('client_calls', models.IntegerField(default=1)),
                ('from_whatsapp', models.BooleanField(blank=True, default=False)),
                ('call_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='registercall.CallRequest')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='management.HelperCategory')),
                ('language', models.ManyToManyField(blank=True, to='ivr.Language')),
                ('taskcategory', models.ManyToManyField(blank=True, default=None, related_name='taskcategory', to='management.CategorySubcategory')),
                ('tasksubcategory', models.ManyToManyField(blank=True, default=None, related_name='tasksubcategory', to='management.CategorySubcategory')),
            ],
        ),
        migrations.AddField(
            model_name='followuptask',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_task', to='registercall.Task'),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='f_task', to='registercall.Task'),
        ),
    ]
