# Generated by Django 2.1.5 on 2021-05-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registercall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuptask',
            name='marked_date',
            field=models.DateTimeField(verbose_name='Marked Timestamp'),
        ),
    ]
