#!/usr/bin/env python
"""
Autogenerated manage.py by Django

Default DJANGO_SETTINGS_MODULE is configured to be used as local.
To use production settings use --settings=dtss.settings.production in manage.py commands
"""

import os
import sys
from loguru import logger

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "dtss.settings.local")
    logger.add('demo2_helpline.log', rotation="1 month")
    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
